name = "nav"
account_id = "d8561b9505c7a42ce9d137119ea43cf6"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 静态资源规则
[[rules]]
globs = ["**/*.html", "**/*.css", "**/*.txt"]
type = "Text"
fallthrough = true

# D1 数据库绑定
[[d1_databases]]
binding = "NAV_DB"
database_name = "book"
database_id = "96634e2e-4639-42e6-a6a8-b0395b3f15bc"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "NAV_AUTH"
id = "3138f9b276c54a0aa3db70b55f195808"
